Hybris 18.1
sailfishos-encryption/hwcrypt pull request #4
Opened 2024-06-29 22:45 UTC by b100dian

This should not be merged, but a hybris-18.1 branch should be made for it

2024-06-30 07:57 UTC, rinigus requested changes
I presume branch will be then android-11 . Or is there a reason for having it hybris-18.1?

Re formatting: probably tab/space issue

2024-06-30 07:57 UTC, rinigus commented on main.cpp
> +          std::string(), /* allow input data on finish */
Formatting is off

2024-06-30 07:57 UTC, rinigus commented on main.cpp
> +          std::string(), /* allow input data on finish */
Formatting is off

2024-06-30 21:46 UTC, b100dian commented
> I presume branch will be then android-11 . Or is there a reason for having it hybris-18.1?

Not really - just because it is not mainline I thought about hybris. android-11 would do just fine

> Re formatting: probably tab/space issue

You're right, that wasn't visibile in my editor. Should be fixed now

2024-09-29 06:09 UTC, rinigus commented
Thank you very much. Sorry for delay - android-11 branch has your changes now. Closing here

2024-09-29 06:09 UTC, closed without merging